### ISSUE TITLE
Add flag for git add after generation

### ISSUE THREAD

**Issue by Krakabek** [arodik/makestuff.js#13]
It would be nice if I could add --git when I generate some stuff and all generated files will be added to git staging

**Comment by arodik** [comment]
I'll not add this, however you can implement the same logic by yourself. In v1.3 i'll add the before/after hooks to commands. Hooks receive the information about created files as a second parameter so you can add files to Git manually. 

You can write something like this:
```javascript
const { exec } = require('child_process');
// .... 
executeAfter: function(data, files) {
   const createdFiles = files.created.join(" ");
   exec(`git add ${createdFiles}`, (err, stdout, stderr) => {
      if (err) {
         console.error("Error during adding files to Git", err);
         return;
      }

      // the *entire* stdout and stderr (buffered)
      console.log("Files are successfully added to Git");
   });
}
```

**Comment by arodik** [comment]
I'll close the issue after releasing v1.3
